# Generated by Django 5.1.6 on 2025-02-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_staff_alter_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('TotalBeds', models.IntegerField()),
                ('AvailableBeds', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='firstname',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='hiredate',
            new_name='HireDate',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='lastname',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='phonenumber',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='position',
            new_name='Position',
        ),
    ]
